name: Merge Upstream

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: no-sys-tray
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/DevilXD/TwitchDropsMiner.git
          git fetch upstream
      
      - name: Check for changes
        id: check-changes
        run: |
          # Check if there are any new commits in upstream/master
          BEHIND=$(git rev-list --count HEAD..upstream/master)
          echo "behind=$BEHIND" >> $GITHUB_OUTPUT
          echo "Commits behind upstream: $BEHIND"
      
      - name: Merge upstream changes
        if: steps.check-changes.outputs.behind > 0
        run: |
          echo "Merging ${{ steps.check-changes.outputs.behind }} new commits from upstream"
          git merge upstream/master --no-edit
      
      - name: Push changes
        if: steps.check-changes.outputs.behind > 0
        run: |
          git push origin no-sys-tray
      
      - name: Trigger CI workflow
        if: steps.check-changes.outputs.behind > 0
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: upstream-merged
      
      - name: Create summary
        run: |
          if [ "${{ steps.check-changes.outputs.behind }}" -gt 0 ]; then
            echo "✅ Successfully merged ${{ steps.check-changes.outputs.behind }} commits from upstream" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ No new commits to merge from upstream" >> $GITHUB_STEP_SUMMARY
          fi
